apiVersion: batch/v1
kind: Job
metadata:
  name: hello
  namespace: syn-system-upgrade-controller
spec:
  template:
    # This is the pod template
    spec:
      containers:
      - name: hello
        image: kidswiss/ubuntu-update:14052020
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /host
            name: host
      volumes:
        - name: host
          hostPath:
              path: /
      restartPolicy: OnFailure
