# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: bionic
#   namespace: system-upgrade
# type: Opaque
# stringData:
#   upgrade.sh: noop

---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: bionic
  namespace: system-upgrade
spec:
  concurrency: 1
  nodeSelector:
    matchExpressions:
      - {key: plan.upgrade.cattle.io/bionic, operator: Exists}
  serviceAccountName: system-upgrade
  # secrets:
  #   - name: bionic
  #     path: /host/run/system-upgrade/secrets/bionic
  drain:
    force: true
  channel: http://192.168.5.42:8091/
  #version: "24042020"
  upgrade:
    image: projectsyn/suc-ubuntu-bionic
    #command: ["chroot", "/host"]
    command: ["/run.sh"]
