{
 "title": "SUC overview",
 "time": { "from": "2020-04-29T12:08:45.989Z", "to": "2020-04-29T15:00:13.206Z" },
 "panels": [
  {
   "title": "Upgrade Jobs completed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_job_status_succeeded{namespace=\"system-upgrade\"} == 1) by (node)",
     "legendFormat": "Nodes completed"
    },
    { "expr": "sum(kube_node_info)", "legendFormat": "Nodes" },
    {
     "expr": "count(kube_job_status_failed{namespace=\"system-upgrade\"} > 1) by (node) ",
     "legendFormat": "Jobs failed"
    },
    {
     "expr": "sum(kube_job_status_active{namespace=\"system-upgrade\"} == 1) by (node)",
     "legendFormat": "Running Jobs"
    }
   ]
  },
  {
   "title": "Cordoned Nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)",
     "legendFormat": "Cordoned nodes"
    },
    { "expr": "count(kube_node_info)", "legendFormat": "Total nodes" }
   ]
  },
  {
   "title": "Node table",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max(kube_node_labels) by (label_plan_upgrade_cattle_io_bionic,node)",
     "legendFormat": "{{node}}: {{label_plan_upgrade_cattle_io_bionic}}"
    }
   ]
  }
 ]
}