name: Build images for Docker Hub
on:
  schedule:
    - cron: '0 9 * * 1' # every monday at 09:00
  push:
    branches:
      - master

jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ubuntu_version: 18.04
            ubuntu_name: bionic
          - ubuntu_version: 20.04
            ubuntu_name: focal
          - ubuntu_version: 22.04
            ubuntu_name: jammy
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASSWORD }}"
      - name: Set Tag for scheduled build
        run: echo "TAG=$(date +%Y%m%d)" >> ${GITHUB_ENV}
        if: ${{ github.event_name == 'schedule' }}
      - name: Set Tag for build of master branch
        run: echo "TAG=latest" >> ${GITHUB_ENV}
        if: ${{ github.event_name == 'push' }}
      - name: Build Image for Ubuntu ${{ matrix.ubuntu_name }}
        run: docker build --build-arg ubuntu_version=${{ matrix.ubuntu_version }} -t projectsyn/suc-ubuntu-${{ matrix.ubuntu_name }}:$TAG .
      - name: Push Image
        run: docker push projectsyn/suc-ubuntu-${{ matrix.ubuntu_name }}:$TAG

  # Adapted from https://github.com/liskin/gh-workflow-keepalive to
  # avoid depending on that action.
  keepalive:
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Enable workflow through API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          case "${GITHUB_WORKFLOW_REF:?}" in
            "${GITHUB_REPOSITORY:?}"/.github/workflows/*.y*ml@*) ;;
            *) false ;;
          esac
          workflow="${GITHUB_WORKFLOW_REF%%@*}"
          workflow="${workflow#${GITHUB_REPOSITORY}/.github/workflows/}"
          gh api -X PUT "repos/${GITHUB_REPOSITORY}/actions/workflows/${workflow}/enable"
